/**
 * This file generated by Apso.
 */
import { CategoryModule } from './Category/Category.module';
import { ArticleModule } from './Article/Article.module';

export default [CategoryModule, ArticleModule];
