/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Category } from './Category.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { CategoryService } from './Category.service';
import { CategoryController } from './Category.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Category])],
  providers: [CategoryService],
  exports: [CategoryService],
  controllers: [CategoryController],
})
export class CategoryModule {}
