/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Article } from './Article.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ArticleService } from './Article.service';
import { ArticleController } from './Article.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Article])],
  providers: [ArticleService],
  exports: [ArticleService],
  controllers: [ArticleController],
})
export class ArticleModule {}
